### PR TITLE
Add allthedoll slide

### PR DESCRIPTION
**Pull request by allthedoll**
This PR adds a slide, created by @allthedoll. 🌮 🦄

### CODE REVIEW

**Comment by Caseycarhart** [comment]
Matroyska dolls are like nested Case statements?

**Comment by allthedoll** [comment]
> Matroyska dolls are like nested Case statements?

🤣

**Review by Caseycarhart — COMMENTED** [review]
nice title

**Comment by Caseycarhart** [comment]
ask l


ask Linus what he says!

**Pull request merged**
